### PR TITLE
Adjust to RTD's upcoming addon changes

### PR DESCRIPTION
**Pull request by glatterf42**
Starting on October 7, [RTD will switch to RTD Addons](https://about.readthedocs.com/blog/2024/07/addons-by-default/) for sphinx projects, too. They have identified that this is going to impact message_ix and suggest to change our configuration file in almost exactly the way this PR does. I have [enabled Addons temporarily on RTD](https://app.readthedocs.com/dashboard/iiasa-energy-program-message-ix/addons/edit/) and intend to use this PR to make any adjustments necessary to keep our docs building as expected. 

## How to review

- Read the diff and note that the CI checks all pass.
- Look at the docs built from this PR and confirm they are what we want/expect.

## PR checklist

- [x] Continuous integration checks all ✅
- [x] Add, expand, or update documentation.

### CODE REVIEW

**Comment by glatterf42** [comment]
This project didn't have the setting to build a version of this PR's docs on RTD, which I changed for the moment. I'll try closing and re-opening this PR to see if this triggers the build process.

**Comment by glatterf42** [comment]
It does :tada: 

This raises the question, though: what does the GitHub CI give us that the RTD check doesn't provide? A faster runtime, for sure, but RTD then also compiles the pages so that we can look at them: https://iiasa-energy-program-ece-docs--12.com.readthedocs.build/scenario-databases.html

Please note that visual changes like the flyout menu switching to the right side are expected (see migration notes). RTD wants to update their theme to offer keeping it on the left, but for now, this change is intentional.

With that in mind, the docs look great to me and don't produce any error message :)

**Comment by danielhuppmann** [comment]
I didn't know that there is an RTD-workflow - first time I see this... But super-cool, and indeed, ok to remove the GitHub workflow if RTD has a native solution.

I'm wondering if this will also happen on pyam, message_ix, etc.? And if this only works on PRs from the upstream repository or also from forks?

**Review by danielhuppmann — COMMENTED** [review]
Suggest to remove the GitHub Actions workflow if this is not necessary any more

**Comment by glatterf42** [comment]
The workflow installs the package via `pip -r requirements.txt` and then builds the docs via `make html`. RTD does the same, except for calling `sphinx html` in the end, which seems fine to me.

RTD sent out an email about message_ix, ece-docs, and ece-teaching being affected. I have taken care of all of them. For pyam, it's not listed as a project under https://readthedocs.com/organizations/iiasa-energy-program/, so I did not get notified. If its configuration is similar to the one here or on message_ix, the migration is not difficult, though.

The RTD build process is triggered for PRs from forks, too, and it doesn't rely on GitHub secrets or so, so it's usually successful on message_ix :)

**Review by danielhuppmann — APPROVED** [review]
Thanks @glatterf42!

**Pull request merged**
